create table if not exists public.contact_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc'::text, now()),
  nombre text not null check (char_length(nombre) between 2 and 120),
  empresa text not null check (char_length(empresa) between 2 and 160),
  cargo text check (cargo is null or char_length(cargo) <= 120),
  correo text not null check (char_length(correo) between 5 and 254),
  telefono text check (telefono is null or char_length(telefono) <= 40),
  pais text check (pais is null or char_length(pais) <= 100),
  tema text not null check (char_length(tema) between 2 and 120),
  mensaje text not null check (char_length(mensaje) between 10 and 5000),
  estado text not null default 'nuevo' check (estado in ('nuevo', 'contactado', 'cerrado')),
  origen text not null default 'website'
);

alter table public.contact_submissions enable row level security;

revoke all on table public.contact_submissions from anon, authenticated;
grant insert on table public.contact_submissions to anon, authenticated;
grant usage, select on sequence public.contact_submissions_id_seq to anon, authenticated;

drop policy if exists "Public visitors can submit contact requests" on public.contact_submissions;
create policy "Public visitors can submit contact requests"
on public.contact_submissions
for insert
to anon, authenticated
with check (
  char_length(nombre) between 2 and 120
  and char_length(empresa) between 2 and 160
  and char_length(correo) between 5 and 254
  and char_length(mensaje) between 10 and 5000
  and estado = 'nuevo'
  and origen = 'website'
);

comment on table public.contact_submissions is
  'Consultas enviadas desde el formulario público de Gambin Partners.';
